-- One-time: envio_ativo foi definido como 0 na implantação inicial desta feature.
-- Não reexecutar UPDATE aqui — o migrate roda todos os .sql a cada deploy e apagaria a configuração salva pelo usuário.
