CREATE TABLE IF NOT EXISTS smtp_config (
  id INT PRIMARY KEY,
  host VARCHAR(255) NOT NULL DEFAULT '',
  port INT NOT NULL DEFAULT 587,
  secure TINYINT(1) NOT NULL DEFAULT 0,
  user VARCHAR(255) NOT NULL DEFAULT '',
  password_ciphertext TEXT NULL,
  from_email VARCHAR(255) NOT NULL DEFAULT '',
  from_name VARCHAR(120) NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 0,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO smtp_config (id, host, port, secure, ativo)
VALUES (1, '', 587, 0, 0);
